model:
  name: egnn_denoiser
  params:
    # Denoiser-specific parameters
    elements: 
      - Si
    node_attrs: true
    # EGNN-related parameters
    coords_range: 6.0
    hidden_nf: 128
    n_coords: 8
    n_layers: 8
    normalization_factor: 40.0
    r_cut: 6.5
    sin_embedding: false
    sin_embedding_time: false
    tanh: false
    residual: true

scheduler:
  name: sde_ve
  params:
    sigma_max_pos: 1.7
    sigma_max_el: 1.5
    noise_schedule_el: cosine
    t_min: 0.01
    t_max: 0.99

loss:
  name: epsilon_diff
  params:
    norm_type: l2
    position_weight: 1.0
    element_weight: 0.5

load:
  enabled: false
  name: "a-Si/anneal/egnn"
  epoch: 200

train:
  enabled: true
  data:
    dataset:
      target_density: null
      source:
        name: extxyz
        params:
          file: datasets/a-Si/Si-anneal2.extxyz
    dataloader:
      batch_size: 4
      num_workers: 0
      shuffle: true
    collate: {}
  params:
    lr: 1.e-3
    optimizer_name: adam
    num_epochs: 1000
    save:
      name: "a-Si/anneal/egnn"
      epoch: 100

infer:
  enabled: false
  data:
    dataset:
      target_density: null
      index: ':500'
      source:
        name: extxyz
        params:
          file: datasets/a-Si/Si-anneal2.extxyz
    dataloader:
      batch_size: 4
      num_workers: 0
      shuffle: false
    collate: {}
  params:
    from_random_noise: true
    n_steps: 200
    non_stochastic: false
    con_weight: 0.0
    save:
      name: "a-Si/anneal/egnn"
      enable_log: false
      trajectories:
        enabled: true
        batches: [0]

